### 🆕 Регистрация нового пользователя
POST http://localhost:8000/api/register/
Content-Type: application/json

{
  "username": "{{username}}",
  "email": "{{email}}",
  "password": "{{password}}"
}


### 🔑 Получить токен
POST http://localhost:8000/api/login/
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}


### 🧾 Создание checkout (вставь access_token после запроса выше)
POST http://localhost:8000/api/create_checkout/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{}

### 👤 Посмотреть свою подписку
GET http://localhost:8000/api/subscription_status/
Authorization: Bearer {{access_token}}

### 💎 Доступ к премиум-вью
GET http://localhost:8000/api/premium_content/
Authorization: Bearer {{access_token}}
